### PR TITLE
Added Bot custom action template for VS2022

### PR DESCRIPTION
**Pull request by rvinothrajendran**
Added Bot Custom action template for VS2022

### CODE REVIEW

**Comment by stephanbisser** [comment]
@rvinothrajendran sorry for the delay, would you mind adding a readme file so people will know what it does and how to use it?

**Comment by rvinothrajendran** [comment]
> @rvinothrajendran sorry for the delay, would you mind adding a readme file so people will know what it does and how to use it?

No problem @stephanbisser , I will update the file , Thank you

**Comment by rvinothrajendran** [comment]
@stephanbisser readme file has updated , Kindly check it.
Thank you

**Comment by stephanbisser** [comment]
Thx @rvinothrajendran!

**Pull request merged**
