### PR TITLE
Added chatdown-glob package for multiple chatdown file processing

### PR DESCRIPTION
**Pull request by szul**

### CODE REVIEW

**Review by garypretty — APPROVED** [review]
Nice work @szul looks useful.  The only thing I was going to suggest is maybe adding an example of the resulting transcript file somewhere?

**Comment by szul** [comment]
@garypretty Yeah, I'm going to add some tests, but you're right, and example chatdown/transcript would be good.

**Comment by szul** [comment]
@jamesemann @arafattehsin Let me know if either of you have any input on this quick tool. I know James has some Node experience, so I added him as a reviewer. If there's no objections, I'll go ahead and merge this in.  I used a `packages` folder inside of the root folder rather than `libraries` for this one because we might want to look into using `lerna` to do multi-deployments for the Node packages/code. It was designed to work with monorepos, but they require a specific structure... Just thinking ahead. Microsoft is now using it for their `botbuilder-tools`.

**Comment by jamesemann** [comment]
This looks good @szul - ran it against a couple of sample chatdown files (with attachments) and it generated a transcript. Will try tomorrow with some real chatdown files, but for now I think we are good to merge this 👍

**Comment by szul** [comment]
@jamesemann Cool... I'm going to write some tests for it using `mocha` and a bunch of Chatdown files in different directories with different parameters. Might need some tweaks to the filename and directory parsing, but the first param as a glob just uses glob syntax, so we should be good there. Second param might need some tweaking.

**Pull request merged**
